function book(entry) {
  return {
    hype: 0,
    doubtNote: "",
    helpfulBefore: [],
    keywords: [],
    ...entry,
  };
}

// Page counts are round lengths for a common paperback. Scores are this
// council's editorial taste, used so a disagreement can be checked.
export const BOOKS = [
  book({
    id: "frankenstein",
    title: "Frankenstein",
    author: "Mary Shelley",
    year: 1818,
    kind: "fiction",
    pages: 280,
    difficulty: 2,
    pleasures: 4,
    finishability: 4,
    influence: 5,
    challenge: 3,
    subjects: ["fiction", "science", "creation", "romanticism"],
    keywords: ["monster", "experiment", "responsibility", "science"],
    blurb: "A frame narrative in which Victor Frankenstein tells what followed from making a living creature.",
  }),
  book({
    id: "pride-and-prejudice",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    year: 1813,
    kind: "fiction",
    pages: 430,
    difficulty: 2,
    pleasures: 5,
    finishability: 5,
    influence: 5,
    challenge: 2,
    subjects: ["fiction", "marriage", "society", "comedy"],
    keywords: ["romance", "class", "family"],
    blurb: "A comedy of marriage, money, and misjudgment among the Bennet sisters and their neighbors.",
  }),
  book({
    id: "middlemarch",
    title: "Middlemarch",
    author: "George Eliot",
    year: 1871,
    kind: "fiction",
    pages: 880,
    difficulty: 3,
    pleasures: 5,
    finishability: 3,
    influence: 5,
    challenge: 3,
    subjects: ["fiction", "marriage", "vocation", "provincial"],
    keywords: ["town", "reform", "work", "love"],
    blurb: "A provincial English town, several marriages, and the correction of people who meant to do something great.",
  }),
  book({
    id: "crime-and-punishment",
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    year: 1866,
    kind: "fiction",
    pages: 550,
    difficulty: 4,
    pleasures: 4,
    finishability: 3,
    influence: 5,
    challenge: 4,
    subjects: ["fiction", "guilt", "morality", "city"],
    keywords: ["murder", "justice", "conscience", "petersburg"],
    blurb: "A Petersburg student commits a murder he has reasoned himself into, and then has to live inside the reasoning.",
  }),
  book({
    id: "brothers-karamazov",
    title: "The Brothers Karamazov",
    author: "Fyodor Dostoevsky",
    year: 1880,
    kind: "fiction",
    pages: 820,
    difficulty: 4,
    pleasures: 5,
    finishability: 3,
    influence: 5,
    challenge: 5,
    subjects: ["fiction", "faith", "family", "justice"],
    keywords: ["god", "trial", "brothers", "doubt"],
    blurb: "Three brothers, a murdered father, and a trial that puts faith, reason, and desire in the same room.",
  }),
  book({
    id: "mrs-dalloway",
    title: "Mrs Dalloway",
    author: "Virginia Woolf",
    year: 1925,
    kind: "fiction",
    pages: 200,
    difficulty: 4,
    pleasures: 5,
    finishability: 3,
    influence: 5,
    challenge: 4,
    subjects: ["fiction", "consciousness", "city", "time"],
    keywords: ["london", "party", "mortality", "day", "memory"],
    blurb: "One June day in London, from the morning of a party to the party itself, told through the people who cross it.",
  }),
  book({
    id: "their-eyes",
    title: "Their Eyes Were Watching God",
    author: "Zora Neale Hurston",
    year: 1937,
    kind: "fiction",
    pages: 220,
    difficulty: 3,
    pleasures: 5,
    finishability: 4,
    influence: 4,
    challenge: 3,
    subjects: ["fiction", "voice", "marriage", "freedom"],
    keywords: ["florida", "love", "speech"],
    blurb: "Janie Crawford tells a friend about her three marriages and the life she wanted from them.",
  }),
  book({
    id: "the-stranger",
    title: "The Stranger",
    author: "Albert Camus",
    year: 1942,
    kind: "fiction",
    pages: 140,
    difficulty: 2,
    pleasures: 4,
    finishability: 5,
    influence: 4,
    challenge: 3,
    subjects: ["fiction", "absurd", "death", "trial"],
    keywords: ["mortality", "grief", "algiers", "honesty"],
    blurb: "Meursault buries his mother, kills a man on a beach, and is tried for the feeling he did not perform.",
  }),
  book({
    id: "invisible-man",
    title: "Invisible Man",
    author: "Ralph Ellison",
    year: 1952,
    kind: "fiction",
    pages: 580,
    difficulty: 3,
    pleasures: 5,
    finishability: 3,
    influence: 5,
    challenge: 4,
    subjects: ["fiction", "race", "america", "identity"],
    keywords: ["harlem", "visibility", "power"],
    blurb: "An unnamed narrator moves from a Southern college through Harlem and learns how a person is made unseen.",
  }),
  book({
    id: "left-hand-of-darkness",
    title: "The Left Hand of Darkness",
    author: "Ursula K. Le Guin",
    year: 1969,
    kind: "fiction",
    pages: 330,
    difficulty: 3,
    pleasures: 5,
    finishability: 4,
    influence: 4,
    challenge: 3,
    subjects: ["fiction", "science-fiction", "gender", "politics"],
    keywords: ["winter", "envoy", "culture"],
    blurb: "An envoy arrives on Gethen, a planet of permanent winter whose inhabitants are not fixed as men or women.",
  }),
  book({
    id: "beloved",
    title: "Beloved",
    author: "Toni Morrison",
    year: 1987,
    kind: "fiction",
    pages: 320,
    difficulty: 4,
    pleasures: 5,
    finishability: 3,
    influence: 5,
    challenge: 4,
    subjects: ["fiction", "slavery", "memory", "family"],
    keywords: ["ghost", "mother", "ohio", "history"],
    blurb: "Sethe and her daughter Denver live in a house haunted by the child Sethe would not allow to be taken back into slavery.",
  }),
  book({
    id: "remains-of-the-day",
    title: "The Remains of the Day",
    author: "Kazuo Ishiguro",
    year: 1989,
    kind: "fiction",
    pages: 250,
    difficulty: 2,
    pleasures: 5,
    finishability: 5,
    influence: 4,
    challenge: 2,
    subjects: ["fiction", "memory", "service", "regret"],
    keywords: ["butler", "england", "dignity", "duty"],
    blurb: "An English butler looks back on a life of service and on the choice he still calls dignity.",
  }),
  book({
    id: "gilead",
    title: "Gilead",
    author: "Marilynne Robinson",
    year: 2004,
    kind: "fiction",
    pages: 250,
    difficulty: 2,
    pleasures: 5,
    finishability: 4,
    influence: 3,
    challenge: 2,
    subjects: ["fiction", "faith", "family", "mortality"],
    keywords: ["letter", "father", "death", "iowa", "grace"],
    blurb: "An aging Congregationalist minister in Iowa writes a long letter to his young son.",
  }),
  book({
    id: "piranesi",
    title: "Piranesi",
    author: "Susanna Clarke",
    year: 2020,
    kind: "fiction",
    pages: 270,
    difficulty: 2,
    pleasures: 5,
    finishability: 5,
    influence: 2,
    challenge: 2,
    hype: 1,
    subjects: ["fiction", "mystery", "wonder", "memory"],
    keywords: ["labyrinth", "house", "tides", "journal"],
    blurb: "A man who lives among endless statue-lined halls keeps a journal of the tides and of the visitor he calls the Other.",
  }),
  book({
    id: "parable-of-the-sower",
    title: "Parable of the Sower",
    author: "Octavia E. Butler",
    year: 1993,
    kind: "fiction",
    pages: 340,
    difficulty: 3,
    pleasures: 4,
    finishability: 4,
    influence: 4,
    challenge: 3,
    subjects: ["fiction", "science-fiction", "faith", "collapse"],
    keywords: ["california", "future", "community", "journey"],
    blurb: "In a collapsing California, Lauren Olamina walks north, writing a belief as she goes.",
  }),
  book({
    id: "things-fall-apart",
    title: "Things Fall Apart",
    author: "Chinua Achebe",
    year: 1958,
    kind: "fiction",
    pages: 210,
    difficulty: 2,
    pleasures: 4,
    finishability: 4,
    influence: 5,
    challenge: 3,
    subjects: ["fiction", "colonialism", "community", "tradition"],
    keywords: ["village", "missionaries", "nigeria", "change"],
    blurb: "Okonkwo's standing in his village, and what happens to it when missionaries and a colonial government arrive.",
  }),
  book({
    id: "ficciones",
    title: "Ficciones",
    author: "Jorge Luis Borges",
    year: 1944,
    kind: "fiction",
    pages: 180,
    difficulty: 4,
    pleasures: 5,
    finishability: 4,
    influence: 5,
    challenge: 3,
    subjects: ["fiction", "stories", "infinity", "philosophy"],
    keywords: ["labyrinth", "library", "time", "identity", "metaphysics"],
    blurb: "Short pieces on libraries, labyrinths, memory, and books that exist only inside the story.",
  }),
  book({
    id: "the-dispossessed",
    title: "The Dispossessed",
    author: "Ursula K. Le Guin",
    year: 1974,
    kind: "fiction",
    pages: 390,
    difficulty: 3,
    pleasures: 4,
    finishability: 4,
    influence: 4,
    challenge: 3,
    subjects: ["fiction", "science-fiction", "politics", "utopia"],
    keywords: ["anarchy", "physics", "freedom", "scarcity"],
    blurb: "A physicist travels between a poor anarchist moon and the wealthy planet it orbits.",
  }),
  book({
    id: "meditations",
    title: "Meditations on First Philosophy",
    author: "René Descartes",
    year: 1641,
    kind: "nonfiction",
    pages: 110,
    difficulty: 4,
    pleasures: 3,
    finishability: 3,
    influence: 5,
    challenge: 4,
    subjects: ["philosophy", "knowledge", "doubt", "self"],
    keywords: ["cogito", "god", "mind", "skepticism", "epistemology"],
    blurb: "Six meditations that try to doubt whatever can be doubted, and then see what is left.",
  }),
  book({
    id: "enquiry-hume",
    title: "An Enquiry Concerning Human Understanding",
    author: "David Hume",
    year: 1748,
    kind: "nonfiction",
    pages: 150,
    difficulty: 3,
    pleasures: 3,
    finishability: 4,
    influence: 5,
    challenge: 3,
    helpfulBefore: ["meditations"],
    subjects: ["philosophy", "knowledge", "empiricism", "skepticism"],
    keywords: ["cause", "experience", "miracle", "habit", "epistemology"],
    blurb: "A short enquiry into what experience can support, and into what reason cannot establish on its own.",
  }),
  book({
    id: "groundwork",
    title: "Groundwork of the Metaphysics of Morals",
    author: "Immanuel Kant",
    year: 1785,
    kind: "nonfiction",
    pages: 90,
    difficulty: 5,
    pleasures: 2,
    finishability: 2,
    influence: 5,
    challenge: 5,
    helpfulBefore: ["enquiry-hume"],
    subjects: ["philosophy", "ethics", "duty", "reason"],
    keywords: ["categorical", "imperative", "will", "morality", "kant"],
    blurb: "A short argument that duty comes from a law you could will for everyone, rather than from what you happen to want.",
  }),
  book({
    id: "on-liberty",
    title: "On Liberty",
    author: "John Stuart Mill",
    year: 1859,
    kind: "nonfiction",
    pages: 130,
    difficulty: 3,
    pleasures: 3,
    finishability: 4,
    influence: 5,
    challenge: 3,
    subjects: ["philosophy", "freedom", "politics", "society"],
    keywords: ["liberty", "opinion", "individual", "harm", "speech"],
    blurb: "A defense of individual liberty against the pressure of law and the pressure of opinion.",
  }),
  book({
    id: "the-republic",
    title: "The Republic",
    author: "Plato",
    year: -375,
    kind: "nonfiction",
    pages: 420,
    difficulty: 4,
    pleasures: 3,
    finishability: 2,
    influence: 5,
    challenge: 4,
    subjects: ["philosophy", "justice", "politics", "education"],
    keywords: ["socrates", "city", "soul", "cave", "plato"],
    blurb: "Socrates and his companions build a city in speech, and with it an account of justice and the soul.",
  }),
  book({
    id: "souls-of-black-folk",
    title: "The Souls of Black Folk",
    author: "W. E. B. Du Bois",
    year: 1903,
    kind: "nonfiction",
    pages: 250,
    difficulty: 3,
    pleasures: 4,
    finishability: 3,
    influence: 5,
    challenge: 3,
    subjects: ["essays", "race", "america", "history"],
    keywords: ["double consciousness", "reconstruction", "education"],
    blurb: "Essays on Black life in America after Reconstruction, including Du Bois's account of double consciousness.",
  }),
  book({
    id: "room-of-ones-own",
    title: "A Room of One's Own",
    author: "Virginia Woolf",
    year: 1929,
    kind: "nonfiction",
    pages: 110,
    difficulty: 3,
    pleasures: 5,
    finishability: 4,
    influence: 5,
    challenge: 2,
    subjects: ["essay", "writing", "feminism", "money"],
    keywords: ["women", "literature", "shakespeare"],
    blurb: "An argument, through a fictional narrator, that a woman who writes needs money and a room of her own.",
  }),
  book({
    id: "the-fire-next-time",
    title: "The Fire Next Time",
    author: "James Baldwin",
    year: 1963,
    kind: "nonfiction",
    pages: 110,
    difficulty: 2,
    pleasures: 5,
    finishability: 5,
    influence: 5,
    challenge: 3,
    subjects: ["essays", "race", "america", "religion"],
    keywords: ["letter", "nephew", "harlem", "nation"],
    blurb: "Two essays, one of them a letter to his nephew, on race and religion in America.",
  }),
  book({
    id: "ways-of-seeing",
    title: "Ways of Seeing",
    author: "John Berger",
    year: 1972,
    kind: "nonfiction",
    pages: 160,
    difficulty: 2,
    pleasures: 4,
    finishability: 5,
    influence: 4,
    challenge: 2,
    subjects: ["art", "essays", "seeing", "images"],
    keywords: ["painting", "reproduction", "gaze", "publicity"],
    blurb: "A short book, made with pictures, on how reproduction changes what looking at art comes to.",
  }),
  book({
    id: "death-and-life",
    title: "The Death and Life of Great American Cities",
    author: "Jane Jacobs",
    year: 1961,
    kind: "nonfiction",
    pages: 470,
    difficulty: 3,
    pleasures: 4,
    finishability: 3,
    influence: 5,
    challenge: 2,
    subjects: ["cities", "urbanism", "streets", "politics"],
    keywords: ["sidewalk", "neighborhood", "planning"],
    blurb: "A defense of sidewalks, mixed uses, and the ordinary life of streets, written against urban renewal.",
  }),
  book({
    id: "structure",
    title: "The Structure of Scientific Revolutions",
    author: "Thomas S. Kuhn",
    year: 1962,
    kind: "nonfiction",
    pages: 210,
    difficulty: 4,
    pleasures: 3,
    finishability: 3,
    influence: 5,
    challenge: 4,
    hype: 1,
    doubtNote: "The argument is about normal science and revolution. The phrase that escaped the book is wider than the argument.",
    subjects: ["science", "history", "philosophy", "knowledge"],
    keywords: ["paradigm", "physics", "discovery"],
    blurb: "An account of science as long stretches of normal work, broken by changes of framework.",
  }),
  book({
    id: "selfish-gene",
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    year: 1976,
    kind: "nonfiction",
    pages: 380,
    difficulty: 3,
    pleasures: 4,
    finishability: 4,
    influence: 4,
    challenge: 3,
    hype: 1,
    doubtNote: "The genetics is a real introduction. The metaphor has been asked to explain culture, and that request is the part to doubt.",
    subjects: ["biology", "evolution", "science"],
    keywords: ["gene", "selection", "nature"],
    blurb: "Evolution written from the gene's point of view, for a reader who is not a biologist.",
  }),
  book({
    id: "theory-of-justice",
    title: "A Theory of Justice",
    author: "John Rawls",
    year: 1971,
    kind: "nonfiction",
    pages: 580,
    difficulty: 5,
    pleasures: 2,
    finishability: 2,
    influence: 5,
    challenge: 5,
    helpfulBefore: ["on-liberty", "groundwork"],
    subjects: ["philosophy", "justice", "politics", "ethics"],
    keywords: ["fairness", "veil", "original position", "equality", "liberal"],
    blurb: "A long construction of justice as fairness, built around the original position and the veil of ignorance.",
  }),
  book({
    id: "reasons-and-persons",
    title: "Reasons and Persons",
    author: "Derek Parfit",
    year: 1984,
    kind: "nonfiction",
    pages: 540,
    difficulty: 5,
    pleasures: 3,
    finishability: 2,
    influence: 4,
    challenge: 5,
    helpfulBefore: ["groundwork", "on-liberty"],
    subjects: ["philosophy", "identity", "ethics", "persons"],
    keywords: ["death", "future", "self", "mortality", "teletransport"],
    blurb: "Arguments about personal identity, future people, and moral assumptions that do not survive contact with either.",
  }),
  book({
    id: "atomic-bomb",
    title: "The Making of the Atomic Bomb",
    author: "Richard Rhodes",
    year: 1986,
    kind: "nonfiction",
    pages: 790,
    difficulty: 3,
    pleasures: 4,
    finishability: 4,
    influence: 4,
    challenge: 3,
    subjects: ["history", "physics", "war", "science"],
    keywords: ["nuclear", "manhattan", "scientists"],
    blurb: "A narrative history of the physics, the people, and the politics behind the first atomic weapons.",
  }),
  book({
    id: "henrietta-lacks",
    title: "The Immortal Life of Henrietta Lacks",
    author: "Rebecca Skloot",
    year: 2010,
    kind: "nonfiction",
    pages: 380,
    difficulty: 2,
    pleasures: 4,
    finishability: 5,
    influence: 3,
    challenge: 2,
    subjects: ["science", "ethics", "biography", "medicine"],
    keywords: ["cells", "consent", "race", "research"],
    blurb: "The life of Henrietta Lacks, the cells taken from her without consent, and the research those cells made possible.",
  }),
  book({
    id: "warmth-of-other-suns",
    title: "The Warmth of Other Suns",
    author: "Isabel Wilkerson",
    year: 2010,
    kind: "nonfiction",
    pages: 620,
    difficulty: 3,
    pleasures: 5,
    finishability: 4,
    influence: 4,
    challenge: 3,
    subjects: ["history", "migration", "america", "race"],
    keywords: ["south", "chicago", "journey"],
    blurb: "A history of the Great Migration, told through three people who left the American South.",
  }),
  book({
    id: "braiding-sweetgrass",
    title: "Braiding Sweetgrass",
    author: "Robin Wall Kimmerer",
    year: 2013,
    kind: "nonfiction",
    pages: 390,
    difficulty: 2,
    pleasures: 5,
    finishability: 4,
    influence: 3,
    challenge: 2,
    hype: 1,
    subjects: ["nature", "science", "essays", "plants"],
    keywords: ["botany", "reciprocity", "indigenous"],
    blurb: "Essays by a botanist and Citizen Potawatomi writer on plants, gift, and scientific training.",
  }),
  book({
    id: "say-nothing",
    title: "Say Nothing",
    author: "Patrick Radden Keefe",
    year: 2019,
    kind: "nonfiction",
    pages: 450,
    difficulty: 2,
    pleasures: 5,
    finishability: 5,
    influence: 2,
    challenge: 2,
    hype: 1,
    subjects: ["history", "ireland", "violence", "reporting"],
    keywords: ["troubles", "belfast", "memory"],
    blurb: "A reported history of the Troubles in Northern Ireland, arranged around the disappearance of Jean McConville.",
  }),
  book({
    id: "sapiens",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    year: 2011,
    kind: "nonfiction",
    pages: 450,
    difficulty: 2,
    pleasures: 4,
    finishability: 4,
    influence: 3,
    challenge: 2,
    hype: 3,
    doubtNote: "A single arc is laid over all of human history. Specialists have disputed a great many of the chapters.",
    subjects: ["history", "humanity", "society"],
    keywords: ["humankind", "overview", "civilization", "species"],
    blurb: "A wide popular history of the human species, from early Homo sapiens through empires, money, and science.",
  }),
  book({
    id: "letters-from-a-stoic",
    title: "Letters from a Stoic",
    author: "Seneca",
    year: 65,
    kind: "nonfiction",
    pages: 250,
    difficulty: 2,
    pleasures: 4,
    finishability: 4,
    influence: 4,
    challenge: 2,
    subjects: ["philosophy", "stoicism", "death", "time"],
    keywords: ["grief", "wealth", "mortality", "letters", "rome"],
    blurb: "A common selection of Seneca's letters on time, grief, wealth, and how to meet death.",
  }),
  book({
    id: "six-easy-pieces",
    title: "Six Easy Pieces",
    author: "Richard Feynman",
    year: 1963,
    kind: "nonfiction",
    pages: 170,
    difficulty: 2,
    pleasures: 5,
    finishability: 5,
    influence: 4,
    challenge: 2,
    subjects: ["physics", "science", "lectures"],
    keywords: ["atoms", "energy", "gravity", "quantum"],
    blurb: "Six of Feynman's 1963 introductory lectures, published together as a short book.",
  }),
  book({
    id: "geb",
    title: "Gödel, Escher, Bach",
    author: "Douglas Hofstadter",
    year: 1979,
    kind: "nonfiction",
    pages: 750,
    difficulty: 4,
    pleasures: 4,
    finishability: 2,
    influence: 4,
    challenge: 4,
    hype: 2,
    doubtNote: "The incompleteness theorem at the center is real. A great deal of the book is a performance wrapped around that theorem.",
    subjects: ["math", "logic", "music", "consciousness"],
    keywords: ["godel", "incompleteness", "self-reference", "patterns"],
    blurb: "Dialogues and chapters braiding Gödel's incompleteness theorem with drawings, music, and self-reference.",
  }),
  book({
    id: "four-thousand-weeks",
    title: "Four Thousand Weeks",
    author: "Oliver Burkeman",
    year: 2021,
    kind: "nonfiction",
    pages: 280,
    difficulty: 1,
    pleasures: 3,
    finishability: 5,
    influence: 2,
    challenge: 1,
    hype: 2,
    doubtNote: "One sharp idea about finitude, published at the length and in the aisle of an advice book.",
    subjects: ["time", "work", "essays"],
    keywords: ["productivity", "mortality", "attention", "weeks"],
    blurb: "An argument that a human life runs about four thousand weeks, and that most advice about time refuses the number.",
  }),
  book({
    id: "the-prince",
    title: "The Prince",
    author: "Niccolò Machiavelli",
    year: 1532,
    kind: "nonfiction",
    pages: 110,
    difficulty: 2,
    pleasures: 3,
    finishability: 4,
    influence: 5,
    challenge: 2,
    hype: 2,
    doubtNote: "Later centuries turned a Florentine briefing into a philosophy the book only partly is.",
    subjects: ["politics", "power", "history"],
    keywords: ["state", "rule", "florence", "virtue"],
    blurb: "A short political briefing, addressed to a Medici prince, on how principalities are gained and held.",
  }),
  book({
    id: "never-at-rest",
    title: "Never at Rest",
    author: "Richard S. Westfall",
    year: 1980,
    kind: "nonfiction",
    pages: 900,
    difficulty: 4,
    pleasures: 3,
    finishability: 2,
    influence: 5,
    challenge: 4,
    subjects: ["history", "science", "biography", "physics"],
    keywords: ["newton", "mathematics", "optics", "gravity"],
    blurb: "The standard scholarly biography of Isaac Newton, and a history of the science he remade.",
  }),
  book({
    id: "invention-of-science",
    title: "The Invention of Science",
    author: "David Wootton",
    year: 2015,
    kind: "nonfiction",
    pages: 770,
    difficulty: 4,
    pleasures: 3,
    finishability: 2,
    influence: 4,
    challenge: 5,
    hype: 1,
    doubtNote: "Wootton treats the scientific revolution as a real rupture. A number of historians think that name was applied later, and more loosely.",
    subjects: ["history", "science", "scientific-revolution"],
    keywords: ["experiment", "astronomy", "discovery"],
    blurb: "A long argumentative history of how science, as a practice of discovery, was invented between 1572 and the early eighteenth century.",
  }),
  book({
    id: "age-of-wonder",
    title: "The Age of Wonder",
    author: "Richard Holmes",
    year: 2008,
    kind: "nonfiction",
    pages: 560,
    difficulty: 2,
    pleasures: 5,
    finishability: 4,
    influence: 3,
    challenge: 2,
    hype: 1,
    subjects: ["history", "science", "biography", "romanticism"],
    keywords: ["herschel", "davy", "banks", "astronomy", "chemistry"],
    blurb: "A narrative history of science in the Romantic decades, told through Banks, the Herschels, and Humphry Davy.",
  }),
  book({
    id: "the-gene",
    title: "The Gene: An Intimate History",
    author: "Siddhartha Mukherjee",
    year: 2016,
    kind: "nonfiction",
    pages: 590,
    difficulty: 3,
    pleasures: 4,
    finishability: 4,
    influence: 3,
    challenge: 3,
    hype: 1,
    subjects: ["history", "science", "biology", "genetics"],
    keywords: ["heredity", "mendel", "dna"],
    blurb: "A history of the science of heredity, from Mendel and Darwin through the race to read the human genome.",
  }),
  book({
    id: "double-helix",
    title: "The Double Helix",
    author: "James D. Watson",
    year: 1968,
    kind: "nonfiction",
    pages: 140,
    difficulty: 2,
    pleasures: 4,
    finishability: 5,
    influence: 4,
    challenge: 3,
    hype: 2,
    doubtNote: "A discoverer's memoir of the race for the structure of DNA. It is vivid, and it is unfair to Rosalind Franklin.",
    subjects: ["history", "science", "biology", "memoir"],
    keywords: ["dna", "crick", "franklin", "cambridge"],
    blurb: "Watson's firsthand history of the discovery of the double helix, written as a race he intends to win.",
  }),
  book({
    id: "longitude",
    title: "Longitude",
    author: "Dava Sobel",
    year: 1995,
    kind: "nonfiction",
    pages: 180,
    difficulty: 1,
    pleasures: 4,
    finishability: 5,
    influence: 3,
    challenge: 1,
    hype: 2,
    doubtNote: "A short, charming history of the longitude problem. A great deal of the astronomy, and the other makers, is left out.",
    subjects: ["history", "science", "navigation", "astronomy"],
    keywords: ["harrison", "chronometer", "clocks"],
    blurb: "A short history of the science of finding longitude at sea, centered on John Harrison's clocks.",
  }),
  book({
    id: "milky-way",
    title: "Coming of Age in the Milky Way",
    author: "Timothy Ferris",
    year: 1988,
    kind: "nonfiction",
    pages: 500,
    difficulty: 3,
    pleasures: 4,
    finishability: 3,
    influence: 3,
    challenge: 3,
    subjects: ["history", "science", "astronomy", "cosmology"],
    keywords: ["cosmos", "physics", "universe"],
    blurb: "A history of the science by which people worked out the size and age of the universe.",
  }),
];

export function bookById(id) {
  return BOOKS.find((entry) => entry.id === id) || null;
}
